services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'RabbitMQ'
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
